# This rule is not used by the project lstmserveroperator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to lstmapps.wuyong7240.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: lstmserveroperator
    app.kubernetes.io/managed-by: kustomize
  name: lstmpredictapp-viewer-role
rules:
- apiGroups:
  - lstmapps.wuyong7240.com
  resources:
  - lstmpredictapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lstmapps.wuyong7240.com
  resources:
  - lstmpredictapps/status
  verbs:
  - get
