apiVersion: lstmapps.wuyong7240.com/v1
kind: LSTMPredictApp
metadata:
  name: lstm-timeserise-predict
  namespace: k8s-learn
  labels:
    app: lstm-timeserise-predict
spec:
  appImage: lstm-predict-server:v1.0
  containerPort: 8080
  backendAppReplicas: 2
  servicePort: 80
  serviceType: NodePort